
CREATE TABLE `USUARIO` (
  `ID` int(4) NOT NULL,
  `LOGIN` varchar(50) NOT NULL,
  `SENHA` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `USUARIO` (`ID`, `LOGIN`, `SENHA`) VALUES
(1, 'xd', 'xd');

ALTER TABLE `USUARIO`
  ADD PRIMARY KEY (`ID`),
  ADD UNIQUE KEY `LOGIN` (`LOGIN`);


ALTER TABLE `USUARIO`
  MODIFY `ID` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

